sick_scan: # configuration for sick_scan_lrs_4xxx: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "192.168.0.1"
    frame_id : "cloud"
    scanner_name : "sick_lrs_4xxx"
    port : 2112
    min_ang : -4.71238898 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_ang : 1.57079632 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    
