sick_scan: # configuration for sick_scan_lms_1xx: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "192.168.0.1"
    frame_id : "cloud"
    scanner_name : "sick_lms_1xx"
    port : 2112
    min_ang : -2.35619449 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_ang : 2.35619449 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
